# Generated by Django 2.2.10 on 2021-03-03 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_poll_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='pos_answers',
            field=models.ManyToManyField(null=True, to='test_task_poll_app.Answer', verbose_name='Ответы'),
        ),
    ]
