# Generated by Django 2.2.10 on 2021-03-03 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_poll_app', '0003_auto_20210303_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='type',
            field=models.CharField(choices=[('1', 'Ответ текстом'), ('2', 'Ответ с выбором одного варианта'), ('3', 'Ответ с выбором нескольких вариантов')], max_length=50, verbose_name='Тип'),
        ),
    ]
