# Generated by Django 2.2.10 on 2021-03-04 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_poll_app', '0006_auto_20210303_2216'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200, null=True, verbose_name='Пользовательский ответ')),
                ('answer_id', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='test_task_poll_app.Answer', verbose_name='ID ответа')),
                ('poll_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task_poll_app.Poll', verbose_name='ID опроса')),
            ],
        ),
        migrations.AlterField(
            model_name='question',
            name='pos_answers',
            field=models.ManyToManyField(blank=True, to='test_task_poll_app.Answer', verbose_name='Ответы'),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=200, verbose_name='Название вопроса'),
        ),
        migrations.AlterField(
            model_name='user',
            name='answers',
            field=models.ManyToManyField(blank=True, to='test_task_poll_app.UserAnswer', verbose_name='Ответы пользователя'),
        ),
        migrations.AddField(
            model_name='useranswer',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='test_task_poll_app.Question', verbose_name='ID вопроса'),
        ),
    ]
