version: '3.7'

services:
  test_task:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./test_task:/test_task
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DEBUG=1