# Generated by Django 2.2.10 on 2021-03-03 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200, verbose_name='Ответ')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_id', models.IntegerField(verbose_name='ID')),
                ('answers', models.ManyToManyField(to='test_task_poll_app.Answer', verbose_name='Ответы пользователя')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Название вопроса')),
                ('type', models.CharField(choices=[(1, 'Ответ текстом'), (2, 'Ответ с выбором одного варианта'), (3, 'Ответ с выбором нескольких вариантов')], max_length=50, verbose_name='Тип')),
                ('pos_answers', models.ManyToManyField(to='test_task_poll_app.Answer', verbose_name='Все ответы')),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя опроса')),
                ('start_date', models.DateTimeField(editable=False, verbose_name='Дата начала')),
                ('end_date', models.DateTimeField(verbose_name='Дата конца')),
                ('description', models.TextField(verbose_name='Описание')),
                ('questions', models.ManyToManyField(to='test_task_poll_app.Question', verbose_name='Вопросы')),
            ],
        ),
    ]
