# Generated by Django 2.2.10 on 2021-03-03 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_poll_app', '0002_auto_20210303_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='answers',
            field=models.ManyToManyField(null=True, to='test_task_poll_app.Answer', verbose_name='Ответы пользователя'),
        ),
    ]
