# Generated by Django 2.2.10 on 2021-03-05 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_poll_app', '0009_auto_20210305_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='answers',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_id',
            field=models.ManyToManyField(blank=True, to='test_task_poll_app.User', verbose_name='ID пользователя'),
        ),
    ]
