# Generated by Django 2.2.10 on 2021-03-05 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_poll_app', '0010_auto_20210305_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='site_id',
            field=models.IntegerField(unique=True, verbose_name='ID'),
        ),
    ]
