# Generated by Django 2.2.10 on 2021-03-05 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_poll_app', '0011_auto_20210305_1646'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useranswer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='test_task_poll_app.User', verbose_name='ID пользователя'),
        ),
    ]
