# Generated by Django 2.2.10 on 2021-03-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('test_task_poll_app', '0012_auto_20210305_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswer',
            name='answer_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='test_task_poll_app.Answer', verbose_name='ID ответа'),
        ),
    ]
